### ISSUE TITLE
 API Authentication Phase 1

### ISSUE THREAD

**Issue by ginone** [malgo-ia/rating-room#9]
* use `x-api-key` header to pass secret api key?
* use `POST /api/login` to pass credentials, get JWT, authenticate following requests with JWT?
* use middleware to authenticate requests?

**Comment by malgo-ia** [comment]
**Phase 1**
- add a password column to the USER table
- add new endpoint for update password `PUT /users/{id}/password`
- POST User request must include a password
- endpoint PUT User is unable to update password
- password must meet security requirements
- in the user table, we store the password as a hash (e.g SHA256 /passlib library )
